### ISSUE TITLE
about the projection

### ISSUE THREAD

**Issue by lzfff12** [namepllet/HandOccNet#11]
How to project the predicted 3D joints back into the image after cropping the image and then match the 2D joints?

**Comment by anilesec** [comment]
Hi @namepllet 

I have an extended question:

by "GT root coordinate" do you mean  ground truth 3d joints root coordinates of that image?

if this is the case, then there is no way to project estimated 3d joints onto image if we don't have GT 3d joints for an input image. Is my understanding correct?

Thanks!
