### ISSUE TITLE
About the MANO params of HO3D datasets

### ISSUE THREAD

**Issue by EAST-J** [namepllet/HandOccNet#14]
Hi, Thanks for your great work! I see that you use manopth to produce the gt verts of the hand.  I notice that you do not sub the wrist of the hand, I wonder the produced gt verts in root-relative coordinates or in camera space coordinates？ 
[            gt_verts, gt_joints = self.mano_layer(th_pose_coeffs=gt_mano_pose, th_betas=gt_mano_shape)](url)
 Like METRO use FreiHAND dataset, METRO sub the wrist.
[        gt_vertices = gt_vertices - gt_3d_root[:, None, :]](url)
If I want to use the HO3D on METRO, should I sub wrist?

**Comment by namepllet** [comment]
We produced GT verts and pred verts in coordinate system defined in MANO.

You will get similar results with and without sub wrist.

In case of METRO, sub wrist would be fine for HO3D.
