### ISSUE TITLE
FPHA dataset

### ISSUE THREAD

**Issue by luhavefun** [namepllet/HandOccNet#17]
Thanks for your excellent work. I checked the references in FPHA part of paper and found that there are several ways to split the data. Could you give a more detailed criteria?

**Comment by namepllet** [comment]
We used action split.

**Comment by luhavefun** [comment]
Thanks for your reply! Sorry to interrupt, i have another question about FPHA. Are the results of FPHA in paper obtained after procrustes alignment

**Comment by lzfff12** [comment]
> Thanks for your reply! Sorry to interrupt, i have another question about FPHA. Are the results of FPHA in paper obtained after procrustes alignment
I also want to ask this question, do you have the answer？

**Comment by namepllet** [comment]
Yes we obtained the results after procrustes alignment.

**Comment by luhavefun** [comment]
Got it, thanks for the reply.
