### ISSUE TITLE
Question about config setting

### ISSUE THREAD

**Issue by MooreManor** [namepllet/HandOccNet#22]
@namepllet

Hi! Handocc is a nice work.

I have some questions about the experiment setting.
1. The batch size in the paper is 24, but from this [line](https://github.com/namepllet/HandOccNet/blob/65c00af06ad81f568a6ad0ff4919f7f1d6c65e44/main/config.py#L27), the batch size in training seems to be 16. 
2. From the [code snippet](https://github.com/namepllet/HandOccNet/blob/65c00af06ad81f568a6ad0ff4919f7f1d6c65e44/main/config.py#L17-L26), it seems that different datasets have different LR decay strategy. Why do you use two different LR strategies for different datasets?

**Comment by namepllet** [comment]
1. In our experiments, batch size 24 and 16 showed similar results but 16 was slightly better. 
2. We searched the best configuration setting for each dataset.
