### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by tushar994** [namepllet/HandOccNet#3]
Can the pre-trained model please be put up, as training it with dataset is heavy and time consuming.

Thank you!

**Comment by namepllet** [comment]
You can download our pre-trained model from [here](https://github.com/namepllet/HandOccNet/blob/master/README.md#test)

**Comment by tushar994** [comment]
sorry, one more question, I cant figure out how to run this model on arbitrary images, rather than the two datasets mentioned, did I miss something?

**Comment by namepllet** [comment]
Please refer to the demo codes.
