### ISSUE TITLE
novel_object_test_list.json

### ISSUE THREAD

**Issue by abigsure** [namepllet/HandOccNet#33]
with open('/home/hongsuk.c/Projects/HandOccNet/main/novel_object_test_list.json', 'r') as f:
    target_img_list_sum = json.load(f)
print("TARGET LENGTH: ", len(target_img_list_sum))
Can you tell me how to download novel_object_test_list.json?

**Comment by dqj5182** [comment]
@abigsure I recommend running the code in the commit version "add demo" from "23 May 2022 01:50". I think the current version of HandOccNet is corrected for HandNeRF paper, which is future work of HandOccNet by HandOccNet authors.

**Comment by hongsukchoi** [comment]
Hi, I am sorry for the mess. Could you delete those lines @namepllet ?

**Comment by namepllet** [comment]
I'm sorry.

I commented out some lines for novel object in DEX_YCB.py
